version: '3.7'

services:
  api:
    container_name: opus-api
    image: node:12
    working_dir: /app
    command: npm run start:dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
  database:
    container_name: opus-database
    image: postgres:12
    env_file:
      - ./.env
    ports:
      - '5432:5432'
